theme: minima
#remote_theme: sylhare/Type-on-Strap
#this paginate didn't seem to do anything
title: Chris Vizes
#this title seems to affect the home page?

header_text: Hello hello
footer_text: Footer text, add some social links chris
paginate: 5